# Copyright (c) 2026, Mohamed Elrefae and contributors
# For license information, please see license.txt.

import frappe

TRANSLATIONS = {
    "en": {
        "dir": "ltr",
        "lang_attr": "en",
        "title": "Construction Sense | Enterprise Construction ERP",
        "description": "Construction Sense is an enterprise ERP platform for BOQ control, cost management, variation orders, procurement, and project execution.",
        "brand": "Construction Sense",
        "nav_platform": "Platform",
        "nav_operations": "Operations",
        "nav_contact": "Contact",
        "login": "Login",
        "eyebrow": "Enterprise Construction ERP",
        "hero_title": "Build with control",
        "hero_copy": "A purpose-built ERP platform for contractors who demand disciplined BOQ management, real-time cost visibility, and audited variation orders from estimate to execution.",
        "hero_cta_login": "Access Workspace",
        "hero_cta_explore": "Explore Platform",
        "metric_boq_label": "BOQ",
        "metric_boq_desc": "Structured scope, rates, quantities, and approvals.",
        "metric_cost_label": "Cost",
        "metric_cost_desc": "Project budgets tied to procurement and accounting.",
        "metric_vo_label": "VO",
        "metric_vo_desc": "Controlled variation orders with audit history.",
        "metric_scope_label": "Scope",
        "metric_scope_desc": "Branch, cost center, and project context enforcement.",
        "platform_h2": "Built for construction governance",
        "platform_p": "Construction Sense extends ERPNext with the operational rules construction teams need: BOQ lifecycle management, controlled project scope, cost discipline, and cleaner daily execution for site and back-office teams.",
        "cap1_h3": "BOQ Structure Management",
        "cap1_p": "Create project BOQs with clear hierarchy, item stages, cost build-up, quantities, units, and locked approval states that protect baseline scope.",
        "cap2_h3": "Project Cost Governance",
        "cap2_p": "Connect materials, labor, equipment, overhead, purchasing, stock, and accounting transactions to project context so budget movement stays visible.",
        "cap3_h3": "Variation Order Control",
        "cap3_p": "Manage scope changes after approval with traceable revisions, validation rules, and approval-ready documentation for project leadership.",
        "ops_h2": "From estimate to invoice.",
        "ops_p": "Give every team the same controlled project record, from tender estimates and BOQ approvals to purchase orders, stock movement, site execution, and commercial changes.",
        "step_plan": "Plan",
        "step_plan_h3": "Define Breakdown",
        "step_plan_p": "Organize activities, branches, cost centers, and project levels before spending begins.",
        "step_estimate": "Estimate",
        "step_estimate_h3": "Build Reliable Cost",
        "step_estimate_p": "Track item quantities, resource requirements, rates, and budget assumptions securely.",
        "step_execute": "Execute",
        "step_execute_h3": "Control Transactions",
        "step_execute_p": "Keep purchasing, stock, timesheets, and journal entries tied to approved scope.",
        "step_govern": "Govern",
        "step_govern_h3": "Approve Changes",
        "step_govern_p": "Route variation orders through auditable rules before they affect delivery.",
        "cta_h2": "Ready to control your projects?",
        "cta_p": "Log in to access Construction Sense and continue managing your operations inside Frappe Cloud.",
        "cta_login": "Secure Login",
        "footer_copy": "© 2026 Construction Sense. Enterprise construction ERP on Frappe Cloud.",
        "footer_platform": "Platform",
        "footer_operations": "Operations",
        "footer_support": "Support",
        "lang_switch_label": "العربية",
    },
    "ar": {
        "dir": "rtl",
        "lang_attr": "ar",
        "title": "Construction Sense | نظام إERP إنشائي للمؤسسات",
        "description": "Construction Sense منصة ERP متكاملة لإدارة جداول الكميات والتحكم في التكاليف وأوامر التغيير والمشتريات وتنفيذ المشاريع.",
        "brand": "Construction Sense",
        "nav_platform": "المنصة",
        "nav_operations": "العمليات",
        "nav_contact": "تواصل معنا",
        "login": "تسجيل الدخول",
        "eyebrow": "نظام ERP إنشائي للمؤسسات",
        "hero_title": "ابنِ بتحكم",
        "hero_copy": "منصة ERP متخصصة للمقاولين الذين يتطلبون إدارة منضبطة لجداول الكميات، ورؤية فورية للتكاليف، وأوامر تغيير مدققة من التقدير حتى التنفيذ.",
        "hero_cta_login": "الدخول إلى النظام",
        "hero_cta_explore": "استكشف المنصة",
        "metric_boq_label": "BOQ",
        "metric_boq_desc": "نطاق منظم، أسعار، كميات، واعتمادات.",
        "metric_cost_label": "التكلفة",
        "metric_cost_desc": "ميزانيات المشاريع مرتبطة بالمشتريات والمحاسبة.",
        "metric_vo_label": "VO",
        "metric_vo_desc": "أوامر تغيير مضبوطة بسجل تدقيق.",
        "metric_scope_label": "النطاق",
        "metric_scope_desc": "فرع، مركز تكلفة، وتطبيق سياق المشروع.",
        "platform_h2": "مبنية لحوكمة الإنشاءات",
        "platform_p": "يوسع Construction Sense نظام ERPNext بالقواعد التشغيلية التي تحتاجها فرق الإنشاء: إدارة دورة حياة BOQ، نطاق مشروع مضبوط، انضباط في التكاليف، وتنفيذ يومي أنظف لفرق الموقع والمكتب الخلفي.",
        "cap1_h3": "إدارة هيكل BOQ",
        "cap1_p": "إنشاء جداول كميات للمشاريع بهيكلية واضحة، مراحل الأصناف، بناء التكلفة، الكميات، الوحدات، وحالات اعتماد مقفلة تحمي النطاق الأساسي.",
        "cap2_h3": "حوكمة تكاليف المشاريع",
        "cap2_p": "ربط المواد والعمالة والمعدات والمصاريف العامة والمشتريات والمخزون وحركات المحاسبة بسياق المشروع ليبقى حركة الميزانية واضحة.",
        "cap3_h3": "التحكم في أوامر التغيير",
        "cap3_p": "إدارة تغييرات النطاق بعد الاعتماد بمراجعات قابلة للتتبع وقواعد تحقق وتوثيق جاهز للاعتماد لقيادة المشروع.",
        "ops_h2": "من التقدير إلى الفاتورة.",
        "ops_p": "امنح كل فريق نفس سجل المشروع المضبوط، من تقديرات المناقصات واعتمادات BOQ إلى أوامر الشراء وحركة المخزون وتنفيذ الموقع والتغييرات التجارية.",
        "step_plan": "تخطيط",
        "step_plan_h3": "تحديد التقسيم",
        "step_plan_p": "تنظيم الأنشطة والفروع ومراكز التكلفة ومستويات المشروع قبل بدء الإنفاق.",
        "step_estimate": "تقدير",
        "step_estimate_h3": "بناء بيانات تكلفة موثوقة",
        "step_estimate_p": "تتبع كميات الأصناف ومتطلبات الموارد والأسعار وافتراضات الميزانية بشكل آمن.",
        "step_execute": "تنفيذ",
        "step_execute_h3": "التحكم في الحركات",
        "step_execute_p": "إبقاء المشتريات والمخزون وساعات العمل والقيود مرتبطة بالنطاق المعتمد.",
        "step_govern": "حوكمة",
        "step_govern_h3": "اعتماد التغييرات",
        "step_govern_p": "تمرير أوامر التغيير عبر قواعد قابلة للتدقيق قبل تأثيرها على التسليم.",
        "cta_h2": "جاهز للتحكم في مشاريعك؟",
        "cta_p": "سجل الدخول للوصول إلى Construction Sense ومواصلة إدارة عملياتك داخل Frappe Cloud.",
        "cta_login": "تسجيل دخول آمن",
        "footer_copy": "© 2026 Construction Sense. نظام ERP إنشائي للمؤسسات على Frappe Cloud.",
        "footer_platform": "المنصة",
        "footer_operations": "العمليات",
        "footer_support": "الدعم",
        "lang_switch_label": "English",
    },
}


def get_context(context):
    lang = frappe.form_dict.get("lang") or "ar"
    if lang not in TRANSLATIONS:
        lang = "en"

    t = TRANSLATIONS[lang]
    context.full_width = 1
    context.lang = lang
    context.lang_dir = t["dir"]
    context.lang_attr = t["lang_attr"]
    context.title = t["title"]
    context.description = t["description"]
    context.t = t
